### ISSUE TITLE
Cannot reach code.quarkus.io/api/extensions behind proxy

### ISSUE THREAD

**Issue by stgiaf** [redhat-developer/vscode-quarkus#292]
When there is a proxy server in the network, quarkus project cannot be created with the following notification message: Unable to reach http://code.quarkus.io/api/extensions.

**Comment by angelozerr** [comment]
@xorye do you think it's easy to fix that (I suppose we need to provide a new settings for that)

**Comment by xorye** [comment]
I'm having trouble reproducing this on my machine but we would probably have to change https://github.com/redhat-developer/vscode-quarkus/blob/master/src/utils/requestUtils.ts

Also, we need to be careful that there's no regression for https://github.com/redhat-developer/vscode-quarkus/pull/48. It would be great if we had vscode tests (not UI tests) for functions in https://github.com/redhat-developer/vscode-quarkus/blob/master/src/utils/requestUtils.ts

**Comment by shaki02** [comment]
Any updates - I'm getting the same issue on vscode using redhat quarkus extension

**Comment by sebastienblanc** [comment]
@angelozerr Hi had suddenly that issue 2 days in the middle of a presentation, I'm not behind a proxy and I really struggle to fix. Even a reinstall of both vscode and the Quarkus extension did not help. Any idea ?

**Comment by angelozerr** [comment]
@sebastienblanc  thanks for reporting this issue. I can reproduce it and we need to investigate the problem. I suspect it's a SSL certificate problem.

It seems that it's the same issue than https://github.com/redhat-developer/vscode-quarkus/issues/401

**Comment by angelozerr** [comment]
@sebastienblanc could you try to use `VSCode Insider` with vscode-quarkus. It seems that it's a bug from vscode which should be fixed for next release. I tried (on Windows OS) and it works.

**Comment by AdamBien** [comment]
I'm facing the same issue: Unable to reach http://code.quarkus.io/api/extensions

**Comment by angelozerr** [comment]
@AdamBien have you tried with `VSCode Insider`?

**Comment by AdamBien** [comment]
You mean Visual Studio Code Insiders? No.

**Comment by angelozerr** [comment]
> You mean Visual Studio Code Insiders? 

Yes

> No.

According to https://github.com/redhat-developer/vscode-quarkus/issues/401#issuecomment-934129304 the bug comes from vscode which has been resolved. By waiting for the vscode release, you can use VSCode Insider which fix it.

**Comment by geziefer** [comment]
@angelozerr I still have the same issue, and it is neither fixed with VSCode 1.62.3, nor with 1.63.0-insider.
I'm not behind a proxy and I tried a newly installed VSCode and Quarkus Extension 1.9.0 on Windows 10.
When trying the default configured http://code.quarkus.io/api/extensions in browser, it redirects me to https and displays the JSON. Configuring https does not change anything.
This for example makes it impossible to use the create quarkus project wizzard, which might be done otherwise, but does not give a good feeling about the extension if the basic connection to API fails.

**Comment by amar-hemmour98** [comment]
I'm having the same issue actually, even using vscode insiders.
Anyone knows how to deal with this ?

**Comment by ess77** [comment]
Experiencing the same issue with version 1.64.2 of VS Code. Still not fixed!

**Comment by rgrunber** [comment]
Does the wizard fail immediately on activating it, on a particular step, or at the very end when all the options have been selected ?

I tried setting up a basic proxy with [tinyproxy](http://tinyproxy.github.io/) (`http://localhost:8888`) and I'm able to generate a Quarkus project with the wizard. Is there some publicly available proxy that could be used to test this out for which the behaviour is reproducible ?

**Comment by geziefer** [comment]
@rgrunber Interestingly, now it works on my machine, I can go through the wizard and it generates a project.
Before, the wizard started and accepted input for build tool, artifact, ... but then failed at the step when selecting quarkus extensions would show.
Note: Actually, I was not behind a proxy but had company VPN active.

**Comment by jonathanvila** [comment]
I'm behind my company VPN and proxy and I have the same issue with VSCode version 1.92.2
